env:
  TERM: alacritty
window:
  padding:
    x: 2
    y: 4
  decorations: buttonless

live_config_reload: true

scrolling:
  history: 0

import:
  - ~/.alacritty/theme.yml

key_bindings:
  - { key: Return,   mods: Shift,   chars: "\x1b[13;2u" }
  - { key: Return,   mods: Control, chars: "\x1b[13;5u" }
