env:
  TERM: alacritty
window:
  padding:
    x: 2
    y: 4
  decorations: buttonless

live_config_reload: true

scrolling:
  history: 0

font:
  normal:
    family: Iosevka Term
    style: Regular
  bold:
    family: Iosevka Term
    style: Bold
  italic:
    family: Iosevka Term
    style: Italic
  size: 12
  use_thin_strokes: true

colors:
  primary:
    background: "0x2c2e34"
    foreground: "0xe2e2e3"

  normal:
    black: "0x181819"
    red: "0xfc5d7c"
    green: "0x9ed072"
    yellow: "0xe7c664"
    blue: "0x76cce0"
    magenta: "0xb39df3"
    cyan: "0xf39660"
    white: "0xe2e2e3"

  bright:
    black: "0x181819"
    red: "0xfc5d7c"
    green: "0x9ed072"
    yellow: "0xe7c664"
    blue: "0x76cce0"
    magenta: "0xb39df3"
    cyan: "0xf39660"
    white: "0xe2e2e3"
